### ISSUE TITLE
Value returned when convert is false

### ISSUE THREAD

**Issue by kevingamaa** [coinconvert/crypto-convert#1]
I'm working with node aplication and when i try to convert  with the value that return is false, but when i set a timeout function the correct value is returned. Follow the example bellow:
![image](https://user-images.githubusercontent.com/37280409/108240572-bd645880-7129-11eb-96f3-168290a7d338.png)
![image](https://user-images.githubusercontent.com/37280409/108240681-d5d47300-7129-11eb-8e44-d90f56b76691.png)

Would you guys can add a promise or a resolution for that?

**Comment by elis-k** [comment]
There is a few seconds delay only in the initial launch of the app until the local cache is created.

I can add a promise for that surely.

**Comment by kevingamaa** [comment]
A promise would be perfect because in a node aplication this would not cache the results in a native way from the API.

**Comment by elis-k** [comment]
```javascript

if(!convert.isReady){
	await convert.ready();
}
convert.BTC.USD(1);
```
