### ISSUE TITLE
loading preset from site url

### ISSUE THREAD

**Issue by kartik01001** [coinconvert/crypto-convert#13]
please add a site feature to load preset to display two currency converter automatically so that no need to select from the drop-down again and again cause i use your website frequently 

example:- coinconvert.net/ltc/usd
this url should load ltc to usd converter web page

**Comment by kartik01001** [comment]
nevermind I found the url:
`https://coinconvert.net/?cryptoSymbolPath=ltc&fiatSymbolPath=usd`

**Comment by el1s7** [comment]
It already works like that. You don't need to use "cryptoSymbolPath" query. If it didn't work for you, it's probably a browser compatibility issue.
