### ISSUE TITLE
[REQUEST] - Including ARS into the fiat currencies

### ISSUE THREAD

**Issue by gastsail** [coinconvert/crypto-convert#8]
For convertion I cannot find my local currency, I'm developing an app and I need this one. Can we add it ?

**Comment by el1s7** [comment]
You have to find and then connect an API which provides the price of ARS in relation to USD or other supported fiats in crypto-convert, maybe check your local banks if they have something like that.

Example: 

```javascript
convert.addCurrency(
	'ARS',  //Currency symbol
	'USD', //The quote fiat price. Must be a supported fiat currency.
	async fetchPrice()=>{
		//...call your api here
		return price;
        },
	5000 //Update interval in ms
);
```
